package evol.elasticsearch.model;

public class Business {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.neighborhood
     *
     * @mbg.generated
     */
    private String neighborhood;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.postal_code
     *
     * @mbg.generated
     */
    private String postalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.latitude
     *
     * @mbg.generated
     */
    private Float latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.longitude
     *
     * @mbg.generated
     */
    private Float longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.stars
     *
     * @mbg.generated
     */
    private Float stars;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.review_count
     *
     * @mbg.generated
     */
    private Integer reviewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.is_open
     *
     * @mbg.generated
     */
    private Integer isOpen;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.id
     *
     * @return the value of business.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.id
     *
     * @param id the value for business.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.name
     *
     * @return the value of business.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.name
     *
     * @param name the value for business.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.neighborhood
     *
     * @return the value of business.neighborhood
     *
     * @mbg.generated
     */
    public String getNeighborhood() {
        return neighborhood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.neighborhood
     *
     * @param neighborhood the value for business.neighborhood
     *
     * @mbg.generated
     */
    public void setNeighborhood(String neighborhood) {
        this.neighborhood = neighborhood == null ? null : neighborhood.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.address
     *
     * @return the value of business.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.address
     *
     * @param address the value for business.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.city
     *
     * @return the value of business.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.city
     *
     * @param city the value for business.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.state
     *
     * @return the value of business.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.state
     *
     * @param state the value for business.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.postal_code
     *
     * @return the value of business.postal_code
     *
     * @mbg.generated
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.postal_code
     *
     * @param postalCode the value for business.postal_code
     *
     * @mbg.generated
     */
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode == null ? null : postalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.latitude
     *
     * @return the value of business.latitude
     *
     * @mbg.generated
     */
    public Float getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.latitude
     *
     * @param latitude the value for business.latitude
     *
     * @mbg.generated
     */
    public void setLatitude(Float latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.longitude
     *
     * @return the value of business.longitude
     *
     * @mbg.generated
     */
    public Float getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.longitude
     *
     * @param longitude the value for business.longitude
     *
     * @mbg.generated
     */
    public void setLongitude(Float longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.stars
     *
     * @return the value of business.stars
     *
     * @mbg.generated
     */
    public Float getStars() {
        return stars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.stars
     *
     * @param stars the value for business.stars
     *
     * @mbg.generated
     */
    public void setStars(Float stars) {
        this.stars = stars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.review_count
     *
     * @return the value of business.review_count
     *
     * @mbg.generated
     */
    public Integer getReviewCount() {
        return reviewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.review_count
     *
     * @param reviewCount the value for business.review_count
     *
     * @mbg.generated
     */
    public void setReviewCount(Integer reviewCount) {
        this.reviewCount = reviewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.is_open
     *
     * @return the value of business.is_open
     *
     * @mbg.generated
     */
    public Integer getIsOpen() {
        return isOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.is_open
     *
     * @param isOpen the value for business.is_open
     *
     * @mbg.generated
     */
    public void setIsOpen(Integer isOpen) {
        this.isOpen = isOpen;
    }
}