package com.yelp.dao.mapper;

import com.yelp.entity.Checkin;
import com.yelp.entity.CheckinExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CheckinMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkin
     *
     * @mbg.generated
     */
    long countByExample(CheckinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkin
     *
     * @mbg.generated
     */
    int deleteByExample(CheckinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkin
     *
     * @mbg.generated
     */
    int insert(Checkin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkin
     *
     * @mbg.generated
     */
    int insertSelective(Checkin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkin
     *
     * @mbg.generated
     */
    List<Checkin> selectByExample(CheckinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkin
     *
     * @mbg.generated
     */
    Checkin selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Checkin record, @Param("example") CheckinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Checkin record, @Param("example") CheckinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Checkin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Checkin record);
}