package com.yelp.dao.mapper;

import com.yelp.entity.Hours;
import com.yelp.entity.HoursExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HoursMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hours
     *
     * @mbg.generated
     */
    long countByExample(HoursExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hours
     *
     * @mbg.generated
     */
    int deleteByExample(HoursExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hours
     *
     * @mbg.generated
     */
    int insert(Hours record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hours
     *
     * @mbg.generated
     */
    int insertSelective(Hours record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hours
     *
     * @mbg.generated
     */
    List<Hours> selectByExample(HoursExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hours
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Hours record, @Param("example") HoursExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hours
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Hours record, @Param("example") HoursExample example);
}