package com.yelp.entity;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.review_count
     *
     * @mbg.generated
     */
    private Integer reviewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.yelping_since
     *
     * @mbg.generated
     */
    private Date yelpingSince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.useful
     *
     * @mbg.generated
     */
    private Integer useful;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.funny
     *
     * @mbg.generated
     */
    private Integer funny;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.cool
     *
     * @mbg.generated
     */
    private Integer cool;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.fans
     *
     * @mbg.generated
     */
    private Integer fans;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.average_stars
     *
     * @mbg.generated
     */
    private Float averageStars;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.compliment_hot
     *
     * @mbg.generated
     */
    private Integer complimentHot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.compliment_more
     *
     * @mbg.generated
     */
    private Integer complimentMore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.compliment_profile
     *
     * @mbg.generated
     */
    private Integer complimentProfile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.compliment_cute
     *
     * @mbg.generated
     */
    private Integer complimentCute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.compliment_list
     *
     * @mbg.generated
     */
    private Integer complimentList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.compliment_note
     *
     * @mbg.generated
     */
    private Integer complimentNote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.compliment_plain
     *
     * @mbg.generated
     */
    private Integer complimentPlain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.compliment_cool
     *
     * @mbg.generated
     */
    private Integer complimentCool;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.compliment_funny
     *
     * @mbg.generated
     */
    private Integer complimentFunny;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.compliment_writer
     *
     * @mbg.generated
     */
    private Integer complimentWriter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.compliment_photos
     *
     * @mbg.generated
     */
    private Integer complimentPhotos;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.review_count
     *
     * @return the value of user.review_count
     *
     * @mbg.generated
     */
    public Integer getReviewCount() {
        return reviewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.review_count
     *
     * @param reviewCount the value for user.review_count
     *
     * @mbg.generated
     */
    public void setReviewCount(Integer reviewCount) {
        this.reviewCount = reviewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.yelping_since
     *
     * @return the value of user.yelping_since
     *
     * @mbg.generated
     */
    public Date getYelpingSince() {
        return yelpingSince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.yelping_since
     *
     * @param yelpingSince the value for user.yelping_since
     *
     * @mbg.generated
     */
    public void setYelpingSince(Date yelpingSince) {
        this.yelpingSince = yelpingSince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.useful
     *
     * @return the value of user.useful
     *
     * @mbg.generated
     */
    public Integer getUseful() {
        return useful;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.useful
     *
     * @param useful the value for user.useful
     *
     * @mbg.generated
     */
    public void setUseful(Integer useful) {
        this.useful = useful;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.funny
     *
     * @return the value of user.funny
     *
     * @mbg.generated
     */
    public Integer getFunny() {
        return funny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.funny
     *
     * @param funny the value for user.funny
     *
     * @mbg.generated
     */
    public void setFunny(Integer funny) {
        this.funny = funny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.cool
     *
     * @return the value of user.cool
     *
     * @mbg.generated
     */
    public Integer getCool() {
        return cool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.cool
     *
     * @param cool the value for user.cool
     *
     * @mbg.generated
     */
    public void setCool(Integer cool) {
        this.cool = cool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.fans
     *
     * @return the value of user.fans
     *
     * @mbg.generated
     */
    public Integer getFans() {
        return fans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.fans
     *
     * @param fans the value for user.fans
     *
     * @mbg.generated
     */
    public void setFans(Integer fans) {
        this.fans = fans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.average_stars
     *
     * @return the value of user.average_stars
     *
     * @mbg.generated
     */
    public Float getAverageStars() {
        return averageStars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.average_stars
     *
     * @param averageStars the value for user.average_stars
     *
     * @mbg.generated
     */
    public void setAverageStars(Float averageStars) {
        this.averageStars = averageStars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.compliment_hot
     *
     * @return the value of user.compliment_hot
     *
     * @mbg.generated
     */
    public Integer getComplimentHot() {
        return complimentHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.compliment_hot
     *
     * @param complimentHot the value for user.compliment_hot
     *
     * @mbg.generated
     */
    public void setComplimentHot(Integer complimentHot) {
        this.complimentHot = complimentHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.compliment_more
     *
     * @return the value of user.compliment_more
     *
     * @mbg.generated
     */
    public Integer getComplimentMore() {
        return complimentMore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.compliment_more
     *
     * @param complimentMore the value for user.compliment_more
     *
     * @mbg.generated
     */
    public void setComplimentMore(Integer complimentMore) {
        this.complimentMore = complimentMore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.compliment_profile
     *
     * @return the value of user.compliment_profile
     *
     * @mbg.generated
     */
    public Integer getComplimentProfile() {
        return complimentProfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.compliment_profile
     *
     * @param complimentProfile the value for user.compliment_profile
     *
     * @mbg.generated
     */
    public void setComplimentProfile(Integer complimentProfile) {
        this.complimentProfile = complimentProfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.compliment_cute
     *
     * @return the value of user.compliment_cute
     *
     * @mbg.generated
     */
    public Integer getComplimentCute() {
        return complimentCute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.compliment_cute
     *
     * @param complimentCute the value for user.compliment_cute
     *
     * @mbg.generated
     */
    public void setComplimentCute(Integer complimentCute) {
        this.complimentCute = complimentCute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.compliment_list
     *
     * @return the value of user.compliment_list
     *
     * @mbg.generated
     */
    public Integer getComplimentList() {
        return complimentList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.compliment_list
     *
     * @param complimentList the value for user.compliment_list
     *
     * @mbg.generated
     */
    public void setComplimentList(Integer complimentList) {
        this.complimentList = complimentList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.compliment_note
     *
     * @return the value of user.compliment_note
     *
     * @mbg.generated
     */
    public Integer getComplimentNote() {
        return complimentNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.compliment_note
     *
     * @param complimentNote the value for user.compliment_note
     *
     * @mbg.generated
     */
    public void setComplimentNote(Integer complimentNote) {
        this.complimentNote = complimentNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.compliment_plain
     *
     * @return the value of user.compliment_plain
     *
     * @mbg.generated
     */
    public Integer getComplimentPlain() {
        return complimentPlain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.compliment_plain
     *
     * @param complimentPlain the value for user.compliment_plain
     *
     * @mbg.generated
     */
    public void setComplimentPlain(Integer complimentPlain) {
        this.complimentPlain = complimentPlain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.compliment_cool
     *
     * @return the value of user.compliment_cool
     *
     * @mbg.generated
     */
    public Integer getComplimentCool() {
        return complimentCool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.compliment_cool
     *
     * @param complimentCool the value for user.compliment_cool
     *
     * @mbg.generated
     */
    public void setComplimentCool(Integer complimentCool) {
        this.complimentCool = complimentCool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.compliment_funny
     *
     * @return the value of user.compliment_funny
     *
     * @mbg.generated
     */
    public Integer getComplimentFunny() {
        return complimentFunny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.compliment_funny
     *
     * @param complimentFunny the value for user.compliment_funny
     *
     * @mbg.generated
     */
    public void setComplimentFunny(Integer complimentFunny) {
        this.complimentFunny = complimentFunny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.compliment_writer
     *
     * @return the value of user.compliment_writer
     *
     * @mbg.generated
     */
    public Integer getComplimentWriter() {
        return complimentWriter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.compliment_writer
     *
     * @param complimentWriter the value for user.compliment_writer
     *
     * @mbg.generated
     */
    public void setComplimentWriter(Integer complimentWriter) {
        this.complimentWriter = complimentWriter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.compliment_photos
     *
     * @return the value of user.compliment_photos
     *
     * @mbg.generated
     */
    public Integer getComplimentPhotos() {
        return complimentPhotos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.compliment_photos
     *
     * @param complimentPhotos the value for user.compliment_photos
     *
     * @mbg.generated
     */
    public void setComplimentPhotos(Integer complimentPhotos) {
        this.complimentPhotos = complimentPhotos;
    }
}