spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/supernebula/config-repo-demo
#            search-paths: repo
#            username:
#            password:

server:
  port: 8121