package com.yelp.entity;

public class EliteYears {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elite_years.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elite_years.year
     *
     * @mbg.generated
     */
    private String year;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elite_years.user_id
     *
     * @return the value of elite_years.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elite_years.user_id
     *
     * @param userId the value for elite_years.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elite_years.year
     *
     * @return the value of elite_years.year
     *
     * @mbg.generated
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elite_years.year
     *
     * @param year the value for elite_years.year
     *
     * @mbg.generated
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }
}