package com.yelp.entity;

public class Hours {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hours.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hours.hours
     *
     * @mbg.generated
     */
    private String hours;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hours.business_id
     *
     * @mbg.generated
     */
    private String businessId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hours.id
     *
     * @return the value of hours.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hours.id
     *
     * @param id the value for hours.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hours.hours
     *
     * @return the value of hours.hours
     *
     * @mbg.generated
     */
    public String getHours() {
        return hours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hours.hours
     *
     * @param hours the value for hours.hours
     *
     * @mbg.generated
     */
    public void setHours(String hours) {
        this.hours = hours == null ? null : hours.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hours.business_id
     *
     * @return the value of hours.business_id
     *
     * @mbg.generated
     */
    public String getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hours.business_id
     *
     * @param businessId the value for hours.business_id
     *
     * @mbg.generated
     */
    public void setBusinessId(String businessId) {
        this.businessId = businessId == null ? null : businessId.trim();
    }
}