package com.yelp.entity;

public class Photo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.business_id
     *
     * @mbg.generated
     */
    private String businessId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.caption
     *
     * @mbg.generated
     */
    private String caption;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.label
     *
     * @mbg.generated
     */
    private String label;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.id
     *
     * @return the value of photo.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.id
     *
     * @param id the value for photo.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.business_id
     *
     * @return the value of photo.business_id
     *
     * @mbg.generated
     */
    public String getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.business_id
     *
     * @param businessId the value for photo.business_id
     *
     * @mbg.generated
     */
    public void setBusinessId(String businessId) {
        this.businessId = businessId == null ? null : businessId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.caption
     *
     * @return the value of photo.caption
     *
     * @mbg.generated
     */
    public String getCaption() {
        return caption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.caption
     *
     * @param caption the value for photo.caption
     *
     * @mbg.generated
     */
    public void setCaption(String caption) {
        this.caption = caption == null ? null : caption.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.label
     *
     * @return the value of photo.label
     *
     * @mbg.generated
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.label
     *
     * @param label the value for photo.label
     *
     * @mbg.generated
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }
}